version: 1.5.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- cmd: nuget restore Source\HtmlRenderer.sln
build:
  parallel: true
  project: Source\HtmlRenderer.sln
  verbosity: minimal
artifacts:
  - path: Build\NuGet\*.nupkg
  - path: Source\Demo\WinForms\bin\Release
    name: Demo.WinForms.$(appveyor_build_version)
  - path: Source\Demo\WPF\bin\Release\
    name: Demo.WPF.$(appveyor_build_version)
