<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MSTest" Version="4.3.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Demo\Common\HtmlRenderer.Demo.Common.csproj" />
        <ProjectReference Include="..\..\HtmlRenderer.WinForms\HtmlRenderer.WinForms.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
    </ItemGroup>

</Project>
